### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by sandoracs** [rogierlommers/logrus-redis-hook#13]
Hello,

Could you provide a license file, please?

**Comment by rogierlommers** [comment]
Done.

**Comment by sandoracs** [comment]
Thank you very much!

**Comment by rogierlommers** [comment]
You're welcome. In what project do you use it?

**Comment by sandoracs** [comment]
Our project is related to Watson Media (https://www.ibm.com/watson/media/). We are working on/testing different log shipping solutions currently.
(I would like to kindly ask you to not reference the project.)

**Comment by rogierlommers** [comment]
Nice. Thanks for the info. I won't reference of course, just interested :).

**Comment by sandoracs** [comment]
Thank you very much! :)
