### ISSUE TITLE
NewHook

### ISSUE THREAD

**Issue by zhaogx** [rogierlommers/logrus-redis-hook#19]
`	return &RedisHook{
		RedisHost:      config.Host,
		RedisPool:      pool,
		RedisKey:       config.Key,
		LogstashFormat: config.Format,
		AppName:        config.App,
		Hostname:       config.Host,  //should be config.HostName
		TTL:            config.TTL,
	}, nil`

**Comment by rogierlommers** [comment]
@zhaogx thanks, if you `pull` / `go get` the latest version, it's fixed.
