### ISSUE TITLE
New Trace log level in logrus

### ISSUE THREAD

**Issue by dgsb** [rogierlommers/logrus-redis-hook#20]
Hello, I'm just opening this issue to let you know, the next release of logrus (v1.2.0) will add a new trace level named Trace below Debug.
Here is the PR for reference sirupsen/logrus#844
You may want to take into account this new level.

**Comment by rogierlommers** [comment]
Thanks! I'll watch logrus. If it's released, I'll upgrade logrus-redis-hook.

**Comment by rogierlommers** [comment]
Hey @dgsb , please update the package; I just added trace level (https://github.com/rogierlommers/logrus-redis-hook/pull/21).
