### ISSUE TITLE
./logrus_redis.go:113:3: undefined: logrus.TraceLevel

### ISSUE THREAD

**Issue by jpfaria** [rogierlommers/logrus-redis-hook#22]

**Comment by rogierlommers** [comment]
You should upgrade the logrus package itself. The trace level was recently added, the hook is making use of that. See here: https://github.com/sirupsen/logrus/issues/629

So what you need to do: `go get -u github.com/sirupsen/logrus`. If you're using vendoring, also update the vendored one.

**Comment by rogierlommers** [comment]
I'll close this one.
