### ISSUE TITLE
redis pubsub ?

### ISSUE THREAD

**Issue by bsergean** [rogierlommers/logrus-redis-hook#24]
Hi there,

I just started using logrus hooks and thought about a redis hook, and obviously someone thought about that first :)
I have been using redis publish / subscribe (and later redis streams), I think both would work well.

I might make a PR to implement this. Thanks !

**Comment by rogierlommers** [comment]
> Hi there,
> 
> I just started using logrus hooks and thought about a redis hook, and obviously someone thought about that first :)
> I have been using redis publish / subscribe (and later redis streams), I think both would work well.
> 
> I might make a PR to implement this. Thanks !

Thanks! Let me know if I can help with something.

**Comment by bsergean** [comment]
Hi, I eventually found out we had a loki instance available (which is grafana logging solution), so it's unlikely I will pursue that redis integration, which would have been fun to do ...

I don't know what you use but loki is cool. It's close to Kibana.

https://grafana.com/oss/loki/

**Comment by rogierlommers** [comment]
Nice, thanks for your suggestion.
