### ISSUE TITLE
log.WithFields

### ISSUE THREAD

**Issue by JC1738** [rogierlommers/logrus-redis-hook#6]
Is there a way to send additional fields to redis. Ultimately would like the ELK stack to pick up additional fields.  The current out of box works, but don't seem to see the With Fields added.

`
    log.WithFields(log.Fields{
        "animal": "walrus",
    }).Info("A walrus appears")
`

**Comment by JC1738** [comment]
I figured out updating createV1Message will allow to do this, wonder if better to supply message struct externally and allow more dynamic adding of fields?

`
    _, ok := entry.Data["animal"]

```
if ok {
    m.Animal = entry.Data["animal"].(string)
}
```

`

**Comment by rogierlommers** [comment]
Thanks @JC1738 for your suggestion and @trunyon for your implementation :). I have merged your PR.

**Comment by JC1738** [comment]
Nice, just noticed this now, must have missed the email notification.  Thanks @trunyon and @rogierlommers
