### ISSUE TITLE
Panic when first log-line is "printed"

### ISSUE THREAD

**Issue by ArildBelsvik** [rogierlommers/logrus-redis-hook#8]
Previously used logrus_logstash hook. Tried to switch to logredis hook. 

panic(0x95c720, 0xc08200a070)
        D:/Go/src/runtime/panic.go:481 +0x3f4
github.com/Sirupsen/logrus.(*Entry).Debug(0x0, 0xc082199f30, 0x1, 0x1)
        d:/data/goprojects/src/github.com/Sirupsen/logrus/entry.go:118 +0x23

**Comment by rogierlommers** [comment]
So no problems?

**Comment by ArildBelsvik** [comment]
Nope, My mistake. Took me 3 - 4 hour to see :(

A

tor. 22. sep. 2016 kl. 22.31 skrev Rogier Lommers <notifications@github.com
